/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.loggerModule.LoggerClass;

public class App {
    private static LoggerClass logger;

    /**
     * Gibt eine Instanz der Logger-Klasse zurueck.
     *
     * @param className Der Name der Klasse, die logt.
     **/
    public static LoggerClass getLogger(String className) {
        return LoggerClass.getLogger(className);
    }

    public static void main(String[] args) {
        // init logger
        logger = LoggerClass.getLogger(App.class.getName());
        logger.logInfo("logger initialized");
        logger.logInfo("ServerMain is started");
    }
}
